server:             # 端口
  port: 3344

spring:
  application:
    name:  springcloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MyGitHubNumber/springcloud-config.git #GitHub上面的git仓库名字