server:
  port: 9527

spring:
  application:
    name: springcloud-zuul-gateway

# 注册到eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

# 配置虚拟访问路径映射
zuul:
  prefix: /jgz                              #访问前缀
  ignored-services: springcloud-dept        #原服务名无法直接访问
  routes:                                   #替代为新的访问地址
    springcloud-dept: /mydept/**


info:
  app.name: zuul-9527
  company.name: jgz-springcloud
  build.artifactId: $project.artifactId$
  build.version: $project.version$
