server:
  port: 80

feign:            #feign开启hystrix服务降级
  hystrix:
    enabled: true

# 将eureka配置到项目中，feign会自动的在服务注册中心中选取合适的服务进行调用，实现负载均衡
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/